permalink: posts/:year-:month-:day-:title.html
include: [".well-known"]
collections:
  projects:
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
navigation:
  -
    name: 消息
    title: News
  -
    name: 特色
    title: Features
  -
    name: 專案
    title: Projects
  -
    name: 下載
    title: Download
  -
    name: 開發
    title: Development
  -
    name: 關於
    title: About
gems:
  - jekyll-feed
feed:
  path: atom.xml
name: 新酷音輸入法
description: "Chewing / 新酷音: 智慧型注音輸入法發展總部"
url: https://chewing.im
author:
  name: Chewing Core Team
  email: chewing-devel@googlegroups.com
